<?php
// module/Album/view/album/album/index.phtml:
$this->headLink()->appendStylesheet($this->basePath('./js/jqueryFileTree/jqueryFileTree.css'));
$this->headScript()->appendFile($this->basePath('./js/jqueryFileTree/jqueryFileTree.js'),
	'text/javascript');
$title = 'FFMpeg and Mp3splt';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
	<div id='container_id'>
		container_id
	</div>

<script type="text/javascript">
	$(document).ready( function() {
		$('#container_id').fileTree({$root: '/home'}, function(file) {
			alert(file);
			file.stopPropagation();
		});
	});
</script>
