<?php
// module/Album/view/album/album/index.phtml:
$this->headLink()->appendStylesheet($this->basePath('./js/phpFileTree/styles/default/default.css'));
$this->headScript()->appendFile($this->basePath('./js/phpFileTree/php_file_tree.js'),
	'text/javascript');
$title = 'FFMpeg and Mp3splt  Scan';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
echo $this->php_file_tree;
?>

