<?php
// module/Mp3/view/mp3/mp3/add.phtml:
$title = 'Add new mp3';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('mp3', array('action' => 'add')));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('title'));
echo $this->formRow($form->get('area'));
echo $this->formRow($form->get('audiofile'));
echo '<br /><br />';
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();