<?php
// module/Mp3/view/mp3/mp3/edit.phtml:
$title = 'Edit mp3';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
	'mp3',
	array(
		'action' => 'edit',
		'id'
		=> $this->id,
		)
	));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('title'));
echo $this->formRow($form->get('area'));
// echo $this->formRow($form->get('audiofilepath'));
echo $this->formRow($form->get('audiofiledir'));
echo $this->formRow($form->get('audiofilename'));
echo $this->formButton($form->get('mybutton')->setAttribute('onclick','window.location =\''.$this->url(
	'mp3',
	array(
		'action' => 'splt',
		'id'
		=> $this->id,
		)
	).'\''));
// echo $this->formButton($form->get('mybutton'));
?>	
<?php
// echo $this->escapeHtml($mp3->audiofilepath);
echo "<br />";
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
