<?php
/**
 * View Layout for DluTwBootstrap Demo
 * @package DluTwBootstrap
 * @copyright David Lukas (c) - http://www.zfdaily.com
 * @license http://www.zfdaily.com/code/license New BSD License
 * @link http://www.zfdaily.com
 * @link https://bitbucket.org/dlu/dlutwbootstrap
 */

$this->headTitle()->setSeparator(' - ')
                  ->setAutoEscape(false);
$basePath = $this->basePath();

//Twitter Bootstrap styles
$this->headLink()->appendStylesheet($basePath . '/css/bootstrap.min.css');
//Twitter Bootstrap style override by DluTwBootstrap
$this->headLink()->appendStylesheet($basePath . '/css/dlu-tw-bootstrap.css');
//Twitter Bootstrap responsive styles
$this->headLink()->appendStylesheet($basePath . '/css/bootstrap-responsive.min.css');
//Google Prettify style
$this->headLink()->appendStylesheet($basePath . '/css/prettify.css');

//jQuery and Twitter Bootstrap JS libraries
$this->inlineScript()->appendFile($basePath . '/js/prettify.js');
$this->inlineScript()->appendFile($basePath . '/js/jquery-1.8.0.min.js');
$this->inlineScript()->appendFile($basePath . '/js/bootstrap.min.js');

echo $this->doctype();
?>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('DluTwBootstrap Demo') ?>
    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
    <!-- Le styles -->
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle(); ?>
    <!-- Scripts -->
    <?php echo $this->headScript() ?>
  </head>
    <body style="padding-top: 60px; padding-bottom: 40px;" onload="prettyPrint();">
    <div class="container">
        <!-- NavBar -->
        <?php
            //Set up the brand link
            $brandLink  = new \Zend\Navigation\Page\Mvc();
            $brandLink->setRoute('dlu_twb_demo_demo');
            $brandLink->setLabel('DluTwBootstrap Demo');
            echo $this->navigation()->twbNavbar()->renderNavbar($this->navbar, null, null,
                                                                $brandLink, null, true, false, true, true, true);

        ?>
        <!-- /NavBar -->
      <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Skeleton Application') ?></a>
          </div>
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <?php //echo $this->navigation('navigation')->menu()->setUlClass('nav navbar-nav'); ?>
            <ul class="nav navbar-nav">
              <li class="dropdown">
                <a href="<?php echo $this->url('album') ?>" class="dropdown-toggle" data-toggle="dropdown">Album <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="<?php echo $this->url('album') ?>">Album</a></li>
                  <li><a href="<?php echo $this->url('album', array('action' => 'fetchaudio')) ?>">Fetch Audio</a></li>
                  <li><a href="#">Something else here</a></li>
                  <li class="divider"></li>
                  <li><a href="#">Separated link</a></li>
                  <li class="divider"></li>
                  <li><a href="#">One more separated link</a></li>
                </ul>
              </li>
              <li class="dropdown">
                <a href="<?php echo $this->url('audio') ?>" class="dropdown-toggle" data-toggle="dropdown">Audio <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="<?php echo $this->url('audio') ?>">Audio</a></li>
                  <li><a href="<?php echo $this->url('audio', array('action' => 'upload')) ?>">Upload Audio</a></li>
                  <li><a href="<?php echo $this->url('audio', array('action' => 'fetchaudio')) ?>">Fetch Audio</a></li>
                  <li><a href="<?php echo $this->url('audio', array('action' => 'readlog')) ?>">Read Mp3Splt Log</a></li>
                  <li><a href="<?php echo $this->url('audio', array('action' => 'scan')) ?>">Audio in Directory</a></li>
                  <li><a href="<?php echo $this->url('audio', array('action' => 'audioindb')) ?>">Audio in Database </a></li>
                  <li><a href="#">Something else here</a></li>
                  <li class="divider"></li>
                  <li><a href="#">Separated link</a></li>
                  <li class="divider"></li>
                  <li><a href="#">One more separated link</a></li>
                </ul>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">FFMpeg<b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="<?php echo $this->url('ffmpeg') ?>">FFMpeg action</a></li>
                  <li><a href="<?php echo $this->url('ffmpeg',  array('action' => 'index')) ?>">List</a></li>
                  <li><a href="#">Something else here</a></li>
                  <li class="divider"></li>
                  <li><a href="#">Separated link</a></li>
                  <li class="divider"></li>
                  <li><a href="#">One more separated link</a></li>
                </ul>
              </li>
            </ul>
          </div><!-- /.navbar-collapse -->
        </nav>
        <div class="container">
          <?php echo $this->content; ?>
          <hr>
          <footer>
            <!--             <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p> -->
          </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
      </body>
      </html>
