    <?php echo $this->doctype(); ?>

    <html lang="en">
    <head>
      <meta charset="utf-8">
      <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

      <?php echo $this->headMeta()
      ->appendName('viewport', 'width=device-width, initial-scale=1.0')
      ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
      ?>

      <!-- Le styles -->
      <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
      ->prependStylesheet($this->basePath() . '/css/style.css')
      ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
      ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

      <!-- Scripts -->
      <?php echo $this->headScript()
      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
      ->prependFile('//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js')
    // ->prependFile($this->basePath() . '/js/jquery.min.js')
      ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
      ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
      ; ?>

    </head>
    <body>
      <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Skeleton Application') ?></a>
          </div>
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <?php //echo $this->navigation('navigation')->menu()->setUlClass('nav navbar-nav'); ?>
            <ul class="nav navbar-nav">
              <li class="active"><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li class="dropdown">
                <a href="<?php echo $this->url('album') ?>" class="dropdown-toggle" data-toggle="dropdown">Album <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="<?php echo $this->url('album') ?>">Album</a></li>
                  <li><a href="<?php echo $this->url('album', array('action' => 'fetchaudio')) ?>">Fetch Audio</a></li>
                  <li><a href="#">Something else here</a></li>
                  <li class="divider"></li>
                  <li><a href="#">Separated link</a></li>
                  <li class="divider"></li>
                  <li><a href="#">One more separated link</a></li>
                </ul>
              </li>
              <li class="dropdown">
                <a href="<?php echo $this->url('audio') ?>" class="dropdown-toggle" data-toggle="dropdown">Audio <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="<?php echo $this->url('audio') ?>">Audio</a></li>
                  <li><a href="<?php echo $this->url('audio', array('action' => 'fetchaudio')) ?>">Fetch Audio</a></li>
                  <li><a href="<?php echo $this->url('audio', array('action' => 'readlog')) ?>">Read Mp3Splt Log</a></li>
                  <li><a href="<?php echo $this->url('audio', array('action' => 'audioindb')) ?>">Audio in Database </a></li>
                  <li><a href="#">Something else here</a></li>
                  <li class="divider"></li>
                  <li><a href="#">Separated link</a></li>
                  <li class="divider"></li>
                  <li><a href="#">One more separated link</a></li>
                </ul>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">FFMpeg<b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="<?php echo $this->url('ffmpeg') ?>">FFMpeg action</a></li>
                  <li><a href="<?php echo $this->url('ffmpeg',  array('action' => 'scan')) ?>">List</a></li>
                  <li><a href="#">Something else here</a></li>
                  <li class="divider"></li>
                  <li><a href="#">Separated link</a></li>
                  <li class="divider"></li>
                  <li><a href="#">One more separated link</a></li>
                </ul>
              </li>
            </ul>
            <form class="navbar-form navbar-right" role="search">
              <div class="form-group">
                <input type="text" class="form-control" placeholder="Search">
              </div>
              <button type="submit" class="btn btn-default">Submit</button>
            </form>
          </div><!-- /.navbar-collapse -->
        </nav>
        <div class="container">
          <?php echo $this->content; ?>
          <hr>
          <footer>
            <!--             <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p> -->
          </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
      </body>
      </html>
